# Generated by Django 2.0.4 on 2018-04-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumComments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='user_first_name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forum',
            name='user_last_name',
            field=models.CharField(default='Dummy Name', max_length=20),
            preserve_default=False,
        ),
    ]
