# Generated by Django 2.0.4 on 2018-04-08 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ForumComments', '0003_auto_20180408_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ForumComments.Forum'),
        ),
    ]
