# Generated by Django 2.0.4 on 2018-04-08 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ForumComments', '0004_auto_20180408_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ForumComments.Forum'),
        ),
    ]
