# Generated by Django 2.0.4 on 2018-04-08 18:47

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ForumComments', '0005_auto_20180408_1822'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='forum',
            managers=[
                ('children', django.db.models.manager.Manager()),
            ],
        ),
    ]
