# Generated by Django 2.0.4 on 2018-04-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForumComments', '0006_auto_20180408_1847'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='forum',
            managers=[
            ],
        ),
    ]
